server:
  port: 8001
mybatis:
  # mybatis配置文件所在路径
  config-location: classpath:mybatis/mybatis.cfg.xml
  # 所有Entity别名类所在包
  type-aliases-package: com.ccic.taobao.entity
  # mapper映射文件
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: taobao-dept
  datasource:
    # 当前数据源的操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    #  mysql驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db_taobao_01
    username: root
    password: 123
    dbcp2:
      # 数据库连接池的最小维持连接数
            min-idle: 5
            # 初始化连接数
            initial-size: 5
            # 最大连接数
            max-total: 5
            # 等待连接获取的最大超时时间
            max-wait-millis: 200
eureka:
  instance:
    instance-id: dept-8001
    prefer-ip-address: true
  client:
  #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

info:
  app.name: taobao-dept
  company.name: www.ccic.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}