server:
  port: 8089

eureka:
  instance:
    instance-id: dept-8089
    prefer-ip-address: true
  client:
    #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

info:
  app.name: taobao-dept-8089
  company.name: www.ccic.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
spring:
  application:
    name: taqobao-consumer-feign